#!/bin/bash
# PreToolUse hook: Block direct edits to generated files.
# These files are auto-generated by scripts and should not be hand-edited.
# Exit 2 = block, Exit 0 = allow.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
    exit 0
fi

if [[ "$FILE_PATH" == */shared/generated/* ]]; then
    echo "Blocked: $FILE_PATH is auto-generated. Do not edit directly — run the generator script instead." >&2
    exit 2
fi

exit 0
